///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package dbms;
//
///**
// *
// * @author Amulya
// */
//public class Student5 extends javax.swing.JFrame {
//
//    /**
//     * Creates new form Student4
//     */
//    public Student5() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        profile_btn = new javax.swing.JButton();
//        TA_btn = new javax.swing.JButton();
//        jSeparator2 = new javax.swing.JSeparator();
//        jSeparator1 = new javax.swing.JSeparator();
//        worklog_btn = new javax.swing.JButton();
//        timetable_btn = new javax.swing.JButton();
//        jLabel6 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTextArea1 = new javax.swing.JTextArea();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
//        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel4.setText("M.E Stipend Management System");
//
//        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
//        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel5.setText("MENU");
//
//        profile_btn.setText("Profile");
//        profile_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                profile_btnActionPerformed(evt);
//            }
//        });
//
//        TA_btn.setText("Mark TA Attendance");
//        TA_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                TA_btnActionPerformed(evt);
//            }
//        });
//
//        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
//
//        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
//
//        worklog_btn.setText("Work-Log");
//        worklog_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                worklog_btnActionPerformed(evt);
//            }
//        });
//
//        timetable_btn.setText("Time Table");
//        timetable_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                timetable_btnActionPerformed(evt);
//            }
//        });
//
//        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
//        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel6.setText("LOGS");
//
//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
//        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
//        jScrollPane1.setViewportView(jTextArea1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(22, 22, 22)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(worklog_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addGroup(layout.createSequentialGroup()
//                                        .addGap(39, 39, 39)
//                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                        .addComponent(TA_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addComponent(timetable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(29, 29, 29)
//                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addGroup(layout.createSequentialGroup()
//                                        .addGap(167, 167, 167)
//                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addGroup(layout.createSequentialGroup()
//                                        .addGap(345, 345, 345)
//                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(179, 179, 179)
//                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(0, 213, Short.MAX_VALUE))
//                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel4)
//                .addGap(18, 18, 18)
//                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(3, 3, 3)
//                        .addComponent(jSeparator2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(41, 41, 41)
//                                .addComponent(jLabel5)
//                                .addGap(63, 63, 63)
//                                .addComponent(profile_btn)
//                                .addGap(64, 64, 64)
//                                .addComponent(TA_btn)
//                                .addGap(72, 72, 72)
//                                .addComponent(timetable_btn)
//                                .addGap(71, 71, 71)
//                                .addComponent(worklog_btn))
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(39, 39, 39)
//                                .addComponent(jLabel6)
//                                .addGap(68, 68, 68)
//                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addContainerGap(700, Short.MAX_VALUE))))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void worklog_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worklog_btnActionPerformed
//        // TODO add your handling code here:
//        this.setVisible(false);
//        new Student5().setVisible(true);
//    }//GEN-LAST:event_worklog_btnActionPerformed
//
//    private void timetable_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetable_btnActionPerformed
//        // TODO add your handling code here:
//                this.setVisible(false);
//        new Student3(co).setVisible(true);
//    }//GEN-LAST:event_timetable_btnActionPerformed
//
//    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
//        // TODO add your handling code here:
//                        this.setVisible(false);
//        new Student1(co).setVisible(true);
//    }//GEN-LAST:event_profile_btnActionPerformed
//
//    private void TA_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TA_btnActionPerformed
//        // TODO add your handling code here:
//                        this.setVisible(false);
//        new Student2(co).setVisible(true);
//    }//GEN-LAST:event_TA_btnActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Student5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Student5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Student5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Student5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Student5().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton TA_btn;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JSeparator jSeparator1;
//    private javax.swing.JSeparator jSeparator2;
//    private javax.swing.JTextArea jTextArea1;
//    private javax.swing.JButton profile_btn;
//    private javax.swing.JButton timetable_btn;
//    private javax.swing.JButton worklog_btn;
//    // End of variables declaration//GEN-END:variables
//}
