/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;
import java.sql.*;
import java.sql.DriverManager;
import java.lang.*;
import java.sql.PreparedStatement;
import java.util.*;
import java.util.concurrent.*;
import java.net.*;
import java.util.Scanner;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Amulya
 */
public class Teacher2 extends javax.swing.JFrame {
Connection co;
int id;

    /**
     * Creates new form Teacher2
     */
    public Teacher2(Connection con,int id) {
        initComponents();
        co=con;
        this.id=id;
        try {  
            String sql1,name,roll;
            //int roll;
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/project", "amulya", "12345678");
            String[] columns = {"RollNo", "Name"};
            Object[][] data;
            sql1="select * from Student";
           TableModel tm=jTable1.getModel();
            PreparedStatement ps = conn.prepareStatement(sql1);
            ResultSet rs = ps.executeQuery();
            //int i =0;
            while(rs.next())
            {
                roll = rs.getString("rollno");
                name = rs.getString("fname");
                
                ((DefaultTableModel) tm).addRow(new Object[]{roll, name,false});
            }        


        }     	
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        wlog_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        bio_btn = new javax.swing.JButton();
        date = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        wlog_btn.setVisible(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        wlog_btn.setText("Work-Log");
        wlog_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wlog_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Biometric  Attendance");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("M.E Stipend Management System");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MENU");

        profile_btn.setText("Profile");
        profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_btnActionPerformed(evt);
            }
        });

        bio_btn.setText("Mark Biomertric Attendance");
        bio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bio_btnActionPerformed(evt);
            }
        });

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));

        jLabel1.setText("DATE");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton1.setText("SUBMIT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null},
//                {null, null, null}
            },
            new String [] {
                "   RollNo", "   Name   ", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("DAY");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bio_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wlog_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(profile_btn)
                        .addGap(64, 64, 64)
                        .addComponent(bio_btn)
                        .addGap(72, 72, 72)
                        .addComponent(wlog_btn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wlog_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wlog_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Teacher3(co,id).setVisible(true);
    }//GEN-LAST:event_wlog_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Teacher1(co,id).setVisible(true);
    }//GEN-LAST:event_profile_btnActionPerformed

    private void bio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bio_btnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bio_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    	int rno=0,rowno=0;int n;
    	
       TableModel tm=jTable1.getModel();
    	boolean check=false;
    	int i=0;
    	
    	
        try {
	            String sql2="Select rollno from Student;";
	            String d= date.getSelectedItem().toString();
	            System.out.println(d);
	        	PreparedStatement ps1 = co.prepareStatement(sql2);
	        	PreparedStatement stmt=co.prepareStatement("select count(*) from Biometric_attendence where rollNO="+"'"+rno+"'"+" AND month="+"?"+";");
	        	ResultSet rs2;
	            ResultSet rs1 = ps1.executeQuery();
	            
	          
	           
	        
	            
	            
	            while(rs1.next())
	            {
	            	System.out.println("h1");
	                rno=rs1.getInt("rollno");
	                stmt.setString(1, d);
	                rs2=stmt.execute();
	                rs2.next();
	                 n=rs2.getInt(1);
	                System.out.println(n);
	                System.out.println("h2");

	            check=(boolean) tm.getValueAt(i, 2);
	                
	               
	                
	                if(n>0)
	                {
	                	System.out.println("h3");
	                 
	                	System.out.println(rno);
	                	if(check==true)
	                	{
	                		System.out.println("PResent");
	                		stmt.executeUpdate("update Biometric_attendence set no_of_days_attended=no_of_days_attended+1 where rollno="+"'"+rno+"'"+" AND month="+"'"+d+"';");
	                	}
	                	System.out.println("h4");
//	                	System.out.println(tm.getValueAt(0, 2));
	                
	                	 //jTable1.
	                	stmt.executeUpdate("update Biometric_attendence set no_of_lectures_taken_place=no_of_lectures_taken_place+1 where rollno="+"'"+rno+"'"+" AND month="+"'"+d+"';");
	                	System.out.println("h5");
	                	
	                	
	                	//System.out.println(i);
	                }
	                else
	                {
	                	if(check==true)
	                	{
	                		stmt.execute("insert into Biometric_attendence(rollNO,month,no_of_days_attended,no_of_lectures_taken_place)"+" values('"+rno+"','"+d+"',1,1);");
	                	}
	                	else
	                	{
	                		stmt.execute("insert into Biometric_attendence(rollNO,month,no_of_days_attended,no_of_lectures_taken_place)"+" values('"+rno+"','"+d+"',0,1);");
	                		
	                	}
	                	//month is new
	                }
	                
	                	i++;
	               
	                
	                
	            }
	            
		       	JOptionPane.showMessageDialog(null,
		       		    "Attendance has been marked!",
		       		    "Attendance",JOptionPane.INFORMATION_MESSAGE);
		       		    
	    
            
        }   
        
        catch (SQLException ex) 
        {
            Logger.getLogger(Teacher2.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
         //       new Teacher2().setVisible(true);
//                try {  
//                    String sql1,name,roll;
//                    //int roll;
//                    Class.forName("com.mysql.jdbc.Driver");
//                   // Connection conn = null;
//                    //Statement stmt = null;
//                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/project", "amulya", "12345678");
//                    String[] columns = {"RollNo", "Name"};
//                    Object[][] data;
//                    sql1="select * from Student";
//                    //sql2="select fname from Student";
//                    DefaultTableModel model = new DefaultTableModel();
//                   
//                    //model.setColumnIdentifiers(columns);
//                    PreparedStatement ps = conn.prepareStatement(sql1);
//                    ResultSet rs = ps.executeQuery();
//                    //int i =0;
//                    if(rs.next())
//                    {
//                        roll = rs.getString("rollno");
//                        name = rs.getString("fname");
//                        model.addRow(new Object[]{roll, name});
//                    }        
//
//                    //jTable1.setModel(model);
//                    //JTable jTable1.setModel(model);
//                    //System.out.println(sql);
//                    //jTable1.setModel(model);
////                    Integer rno;
////                    String nm;
////                    //TableModel tm=jTable1.getModel();
////                    TableModel tm = jTable1.getModel();
////                    for (int i = 0; i < tm.getRowCount(); i++)
////                    {
////                        for (int j = 0; j < tm.getColumnCount(); j++)
////                        {
////                            //rno=(Integer)tm.getValueAt(i, j);
////                            //nm=(String)tm.getValueAt(i,j+1);
////                            
////                            
////                        }
////                    }
//
//                    //new Login(con).setVisible(true);
//
//                }     	
//                catch(Exception e){}

                
            }
        });
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bio_btn;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton profile_btn;
    private javax.swing.JButton wlog_btn;
    // End of variables declaration//GEN-END:variables
}
